AWSTemplateFormatVersion: 2010-09-09

Description: |
  Create Statis Kitten Website 

#Parameters:
  
Resources:

  WebSecGRP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and HTTP from internet" # Required
      GroupName: "web-sec-grp"
      SecurityGroupIngress: 
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 80
          ToPort: 80
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 22
          ToPort: 22

  webserver:
    Type: AWS::EC2::Instance
    Properties:
      Tags: 
        - Key: "String"
          Value: "String"
      
      AdditionalInfo: "String"
      Affinity: "String"
      AvailabilityZone: "String"
      BlockDeviceMappings: 
        - DeviceName: "String"
          Ebs:
            DeleteOnTermination: false
            Encrypted: false
            Iops: "Number"
            KmsKeyId: "String"
            SnapshotId: "String"
            VolumeSize: "Number"
            VolumeType: "String"
          NoDevice: "JSON"
          VirtualName: "String"
      CpuOptions:
        CoreCount: "Number"
        ThreadsPerCore: "Number"
      CreditSpecification:
        CPUCredits: "String"
      DisableApiTermination: false
      EbsOptimized: false
      ElasticGpuSpecifications: 
        - Type: "String"
      ElasticInferenceAccelerators: 
        - Count: "Number"
          Type: "String"
      EnclaveOptions:
        Enabled: false
      HibernationOptions:
        Configured: false
      HostId: "String"
      HostResourceGroupArn: "String"
      IamInstanceProfile: "String"
      ImageId: "String"
      InstanceInitiatedShutdownBehavior: "String"
      InstanceType: "String"
      Ipv6AddressCount: "Number"
      Ipv6Addresses: 
        - Ipv6Address: "String"
      KernelId: "String"
      KeyName: "String"
      LaunchTemplate:
        LaunchTemplateId: "String"
        LaunchTemplateName: "String"
        Version: "String"
      LicenseSpecifications: 
        - LicenseConfigurationArn: "String"
      Monitoring: false
      NetworkInterfaces: 
        - AssociateCarrierIpAddress: false
          AssociatePublicIpAddress: false
          DeleteOnTermination: false
          Description: "String"
          DeviceIndex: "String"
          GroupSet:
            - "String"
          Ipv6AddressCount: "Number"
          Ipv6Addresses:
            - Ipv6Address: "String"
          NetworkInterfaceId: "String"
          PrivateIpAddress: "String"
          PrivateIpAddresses:
            - Primary: false
              PrivateIpAddress: "String"
          SecondaryPrivateIpAddressCount: "Number"
          SubnetId: "String"
      PlacementGroupName: "String"
      PrivateDnsNameOptions:
        EnableResourceNameDnsAAAARecord: false
        EnableResourceNameDnsARecord: false
        HostnameType: "String"
      PrivateIpAddress: "String"
      PropagateTagsToVolumeOnCreation: false
      RamdiskId: "String"
      SecurityGroupIds: 
        - "String"
      SecurityGroups: 
        - "String"
      SourceDestCheck: false
      SsmAssociations: 
        - AssociationParameters:
            - Key: "String"
              Value:
                - "String"
          DocumentName: "String"
      SubnetId: "String"

      Tenancy: "String"
      UserData: "String"
      Volumes: 
        - Device: "String"
          VolumeId: "String"   

#Outputs: